### ISSUE TITLE
How I can add my Token ?

### ISSUE THREAD

**Issue by ramykatour** [gamba-labs/gamba#33]
How I can add my Token ?

**Comment by doctorsolana** [comment]
At the moment we have gated token listings, but will transition to permissionless token pools very soon at v2.gamba.so

in the meantime you can jump in the discord and request a listing

**Comment by ramykatour** [comment]
Thank you ❤️

**Comment by bone-house** [comment]
Pool creation is now open 👉 [explorer.gamba.so/create](https://explorer.gamba.so/create)

To add the token to your platform (assuming you're using the template), after creating the pool and adding liquidity, add the following to `constants.ts`:

```
export const TOKENS: TokenMeta[] = [
  GambaStandardTokens.sol,
  GambaStandardTokens.usdc,
  {
    mint: new PublicKey('<token mint address>'),
    name: '<token name>',
    symbol: '<token symbol>',
    image: '<token image uri>',
    decimals: <token decimals>,
    baseWager: 1, // How many tokens should be the default wager
  },
]
```

**Comment by ramykatour** [comment]
thank you for reply
