### ISSUE TITLE
Feedback for “Pools”

### ISSUE THREAD

**Issue by QUANGDOTCA** [gamba-labs/gamba#34]
i would like to install this on my page. how do i do this?

**Comment by bone-house** [comment]
Could you elaborate? If you want to use one of the [existing pools](https://explorer.gamba.so/pools) on your platform you can add the token like this, in constants.ts:

```
export const TOKENS: TokenMeta[] = [
  GambaStandardTokens.sol,
  GambaStandardTokens.usdc,
  {
    mint: new PublicKey('JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN'),
    name: 'Jupiter',
    symbol: 'JUP',
    image: 'https://static.jup.ag/jup/icon.png',
    decimals: 6,
    baseWager: 1,
  },
]
```

If you want to create a LP for a new token you have to request it via our Discord at the moment.
